#!/usr/bin/env bash
# Regenerates plugin/skills/migration-core/pinned-actions.json.
#
# Every SHA written here comes from a GitHub API response in this run. Nothing
# is carried over from the previous file and nothing is inferred -- an action
# that fails to resolve is dropped, not guessed. That mirrors the rule the
# migration-core skill applies at migration time.
#
# Requirements: gh (authenticated) + jq. Not run in CI; this is a maintainer
# tool whose output is committed.
#
# Usage: bash scripts/refresh-pinned-actions.sh

set -uo pipefail

cd "$(dirname "$0")/.." || exit 1

OUT="plugin/skills/migration-core/pinned-actions.json"

# Sourced from actual `uses:` occurrences across knowledge/ and plugin/skills/.
# Regenerate the list with:
#   grep -rhoE 'uses:[[:space:]]*[^ ]+/[^ @]+' knowledge/ plugin/skills/ | sort -u
ACTIONS=(
  actions/checkout
  actions/setup-node
  actions/setup-python
  actions/setup-java
  actions/setup-go
  actions/upload-artifact
  actions/download-artifact
  actions/cache
  actions/github-script
  docker/login-action
  docker/build-push-action
  docker/setup-buildx-action
  aws-actions/configure-aws-credentials
  azure/login
  ruby/setup-ruby
  shivammathur/setup-php
  codecov/codecov-action
  softprops/action-gh-release
  peaceiris/actions-gh-pages
  dorny/test-reporter
  slackapi/slack-github-action
  webfactory/ssh-agent
)

command -v gh >/dev/null || { echo "gh not found" >&2; exit 1; }
command -v jq >/dev/null || { echo "jq not found" >&2; exit 1; }
gh auth status >/dev/null 2>&1 || { echo "gh is not authenticated" >&2; exit 1; }

TODAY=$(date -u +%Y-%m-%d)
TMP=$(mktemp)
RESOLVED=0
SKIPPED=0

printf '{\n' >"$TMP"
printf '  "_comment": "Generated by scripts/refresh-pinned-actions.sh. Every sha is an API response, never inferred. Re-run to refresh.",\n' >>"$TMP"
printf '  "resolved_on": "%s",\n' "$TODAY" >>"$TMP"
printf '  "actions": {\n' >>"$TMP"

FIRST=1
for a in "${ACTIONS[@]}"; do
  tag=$(gh api "repos/$a/releases/latest" --jq .tag_name 2>/dev/null)
  if [ -z "$tag" ]; then
    # No releases: fall back to the default branch tip, which is still a real
    # observed SHA rather than a guess.
    sha=$(gh api "repos/$a/commits?per_page=1" --jq '.[0].sha' 2>/dev/null)
    tag=""
  else
    sha=$(gh api "repos/$a/commits/$tag" --jq .sha 2>/dev/null)
  fi

  if ! printf '%s' "$sha" | grep -qE '^[0-9a-f]{40}$'; then
    printf '  skip  %-45s (unresolved)\n' "$a" >&2
    SKIPPED=$((SKIPPED + 1))
    continue
  fi

  [ "$FIRST" -eq 0 ] && printf ',\n' >>"$TMP"
  FIRST=0
  printf '    "%s": { "tag": "%s", "sha": "%s" }' "$a" "$tag" "$sha" >>"$TMP"
  printf '  ok    %-45s %s  %s\n' "$a" "${tag:-<default-branch>}" "${sha:0:12}" >&2
  RESOLVED=$((RESOLVED + 1))
done

printf '\n  }\n}\n' >>"$TMP"

jq . "$TMP" >"$OUT" || { echo "generated invalid JSON" >&2; rm -f "$TMP"; exit 1; }
rm -f "$TMP"

printf '\n%s: %d actions resolved, %d skipped\n' "$OUT" "$RESOLVED" "$SKIPPED" >&2
